[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              ../one/iot_trap.log
    Tag               iot.trap
    Read_from_Head    true
    Refresh_Interval  1
    Rotate_Wait       5
    DB                iot_trap.db
    Parser            iot_json

[OUTPUT]
    Name          http
    Match         iot.trap
    Host          localhost
    Port          5000
    URI           /analyze
    Format        json_lines
    Header        Content-Type application/json
    Retry_Limit   False
